article_reviewer/urls.py
from django.urls import path
from article_reviewer import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'article_reviewer'

urlpatterns = [
    path('contact_us/', views.contact_us, name='contact_us'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('contact_us/', views.contact_us, name='contact_us'),
    path('login/my_account/', views.my_account, name='my_account'),
    path('category/', views.category, name='category'),
    path('article/<slug:article_name_slug>/', views.show_article, name='show_article'),
    path('category/<slug:category_name_slug>/', views.show_category, name='show_category'),

    path('login/my_account/add_article/', views.add_article, name='add_article'),
    path('article/<slug:article_name_slug>/make_rating/', views.make_rating, name='review'),
    path('', views.index, name='index'),
]

article_web_app/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from article_reviewer import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('article_reviewer/', include('article_reviewer.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/article_web_app/add_article.html
{% extends 'article_web_app/base.html' %}
{% load static %}

{% block title_block %}
    Article Reviewer
{% endblock %}

{% block body_block %}
    <h1>Add Article</h1>
    <hr>
    <form id="article_form" method="post" action="{% url 'article_reviewer:add_article' %}" enctype="multipart/form-data">
        {% csrf_token %}
        {{ article_form.as_p }}

    <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock %}

templates/article_web_app/article.html
{% extends 'article_web_app/base.html' %}
{% load static %}

{% block title_block %}
    Article Reviewer
{% endblock %}

{% block body_block %}
    <h2>{{ article.title }}</h2>

    {% if article.picture %}
        <li><a href="{{ article.url }}"><img src="{{ MEDIA_URL }}{{ article.picture }}" alt="{{ article.author }}"  width="400" height="400"/></li></a>
    {% else %}
        <li><a href="{{ article.url }}"><img src="{{ MEDIA_URL }}{{ article.category.picture }}" width="400" height="400"/></li></a>
    {% endif %}
    <li>Url: <a href="{{ article.url }}">{{ article.url }}</a></li>
    <li>Category: {{ article.category }}</li>
    <li>Rating: {{ article.averageRating | floatformat:1 }} / 5</li>

    {% if user.is_authenticated %}
    <br><button onclick="reviewFunction()" class="btn btn-primary"><p style= "font-size:x-large;font-weight: bold;">Click here to make a Review</p></button></br>
    {% endif %}
    <hr>
    <h3>Comments:</h3>
    {% if reviews %}
        <ul>
            {% for review in reviews %}
				 {% if review.rating == 5 %}
                <p style= "font-size:large"><br>{{review.date}}<Strong> : {{review.author}} : <img style="display: inline; margin-top: 0 5px;" src= "{% static "images/5stars.png" %}" width="100" height="20"> </Strong></br></p>
				{% endif %}
				{% if review.rating == 4 %}
                <p style= "font-size:large"><br>{{review.date}}<Strong> : {{review.author}} : <img style="display: inline; margin-top: 0 5px;" src= "{% static "images/4stars.png" %}" width="100" height="20"> </Strong></br></p>
				{% endif %}
				{% if review.rating == 3 %}
                <p style= "font-size:large"><br>{{review.date}}<Strong> : {{review.author}} : <img style="display: inline; margin-top: 0 5px;" src= "{% static "images/3stars.png" %}" width="100" height="20"> </Strong></br></p>
				{% endif %}
				{% if review.rating == 2 %}
                <p style= "font-size:large"><br>{{review.date}}<Strong> : {{review.author}} : <img style="display: inline; margin-top: 0 5px;" src= "{% static "images/2stars.png" %}" width="100" height="20"> </Strong></br></p>
				{% endif %}
				{% if review.rating == 1 %}
                <p style= "font-size:large"><br>{{review.date}}<Strong> : {{review.author}} : <img style="display: inline; margin-top: 0 5px;" src= "{% static "images/1stars.png" %}" width="100" height="20"> </Strong></br></p>
				{% endif %}
				
                <li><p style= font-style:italic >{{review.comment}}</p></li>
            {% endfor %}
        </ul>
    {% endif %}

<script>
function reviewFunction() {
    window.location="{% url 'article_reviewer:review' article.slug%}"
}
</script>
<script>
function getstars(x){
    {% if x == 5 %}
	print("woooooooooooooooooooow")
	return "{% static "images/5stars.png" %}"
	{% endif %}
	{% if x == 4 %}
	return "{% static "images/4stars.png" %}"
	{% endif %}
	{%  if x == 3 %}
	return "{% static "images/3stars.png" %}"
	{% endif %}
	{% if x == 2 %}
	return "{% static 'images/2stars.png' %}"
	{% else %}
	return "{% static 'images/1stars.png' %}"
	{% endif %}
	
}
</script>


{% endblock %}

templates/article_web_app/base.html
<!DOCTYPE html>
{% load static %}

<html>
    <head lang="en">
        <meta charset="utf-8" />
        <title>
            {% block title_block %}
                Article Reviewer
            {% endblock %}
        </title>
        <link rel="stylesheet" type="text/css" href="{% static 'CSS/index.css' %}">
    </head>

    <body>
        
    <div class ="container">
        <div class="left">
            <ul>
                <li class="logo"> <a href="{% url 'article_reviewer:index' %}"><img src="{% static 'images/article-logo.png' %}"></a></li>
                <li class="heading"><h1><a href="{% url 'article_reviewer:index' %}">Article Reviewer</a></h1></li>
            </ul>
        </div>
        
        <div class="right">
            <ul>
                <li><button onclick="categoryFunction()" class="btn btn-primary"> <p style= "font-family: Arial, Helvetica, sans-serif;font-size:x-large;font-style:normal;font-weight: bold;">Categories</p></button></li><p style= "font-size:x-large"> | </p>
                <li><button onclick="contactUsFunction()" class="btn btn-primary"> <p style= "font-family: Arial, Helvetica, sans-serif;font-size:x-large;font-style:normal;font-weight: bold;">Contact Us</p></button></li><p style= "font-size:x-large"> | </p>

                {% if user.is_authenticated %}
                    <li><button onclick="accountPageFunction()" class="btn btn-primary"> <p style= "font-family: Arial, Helvetica, sans-serif;font-size:x-large;font-style:normal;font-weight: bold;">User Profile</p></button></li><p style= "font-size:x-large"> | </p>
                    <li><button onclick="logoutFunction()" class="btn btn-primary"> <p style= "font-family: Arial, Helvetica, sans-serif;font-size:x-large;font-style:normal;font-weight: bold;">Logout</p></button></li>
                {% else %}
                    <li><button onclick="loginFunction()" class="btn btn-primary"> <p style= "font-family: Arial, Helvetica, sans-serif;font-size:x-large;font-style:normal;font-weight: bold;">Login</p></button></li><p style= "font-size:x-large"> | </p>
                    <li><button onclick="signUpFunction()" class="btn btn-primary"> <p style= "font-family: Arial, Helvetica, sans-serif;font-size:x-large;font-style:normal;font-weight: bold;">Sign Up</p></button></li> 
                {% endif %}
            </ul>
        </div>  
    </div>
    <div>
        {% block body_block %}
        {% endblock %}
    </div>


    <script src="{% static "js/jquery-3.3.1.min.js" %}" crossorigin="anonymous"></script>
    <script src="{% static "js/article-jquery.js" %}" crossorigin="anonymous"></script>
            
     </body>

     <script>
        function accountPageFunction() {
            window.location="{% url 'article_reviewer:my_account' %}"
        }
    </script>
    <script>
        function logoutFunction() {
            window.location="{% url 'article_reviewer:logout' %}"
        }
    </script>
    <script>
        function loginFunction() {
            window.location="{% url 'article_reviewer:login' %}"
        }
    </script>
    <script>
        function signUpFunction() {
            window.location="{% url 'article_reviewer:sign_up' %}"
        }
    </script>
    <script>
        function categoryFunction() {
            window.location="{% url 'article_reviewer:category' %}"
        }
    </script>
    <script>
        function contactUsFunction() {
            window.location="{% url 'article_reviewer:contact_us' %}"
        }
    </script>
</html>

templates/article_web_app/category.html
{% extends 'article_web_app/base.html' %}
{% load static %}

{% block title_block %}
    Article Reviewer
{% endblock %}
{% block body_block %}
<link rel="stylesheet" type="text/css" href="{% static 'CSS/category.css' %}">
 <h2 class = "title">Categories</h2>
    <hr/>
    <div>
        {% if categories %}
            <nav>
            {% for category in categories %}
                <div class="category"><a>{{ category.name }}</a></div>
                <div class="popular">
                    {% if articles %}
                        <ul>
                            {% for article in articles %}
                            
                            {%  if article.category.name == category.name %}
                            <div class="IconRatings">
                                       {% if article.picture %}
                             <li><br><img src="{{ MEDIA_URL }}{{ article.picture }}" alt="{{ article.author }}"  width="100" height="100"/></br></li>
                                      {% else %}
                             <li><img src="{{ MEDIA_URL }}{{ article.category.picture }}" width="100" height="100"/></li>
                                      {% endif %}
                            <div class="articleName"><br><a href="{% url 'article_reviewer:show_article' article.slug%}">{{ article.title }}</a></br></div>
                    <br></br>
                    </div>
                            {% endif %}
                        
                            {% endfor %}
                        </ul>
                    {% else %}
                        <strong>There are no articles present.</strong>
                    {% endif %}
                </div>
            {% endfor %}
            </nav>
        {% else %}
            <strong>There are no categories present.</strong>
        {% endif %}
        </div>

{% endblock %}

templates/article_web_app/contact_us.html
{% extends 'article_web_app/base.html' %}
{% load static %}

{% block title_block %}
    Article Reviewer
{% endblock %}

{% block body_block %}
    <h1>Contact Us</h1>
    <h2>Email: 2431345k@student.gla.ac.uk</h2>
{% endblock %}

templates/article_web_app/index.html
{% extends 'article_web_app/base.html' %}
{% load static %}

{% block title_block %}
    Article Reviewer
{% endblock %}
<link rel="stylesheet" type="text/css" href="{% static 'CSS/index.css' %}">
{% block body_block %}

    <li></li>
    <div>
        {% if categories %}
            <nav>
            {% for category in categories %}

            &ensp;<a style= "font-size:x-large;font-weight: bold;" href="{% url 'article_reviewer:category' %}">{{ category.name }}</a>&ensp;

            {% endfor %}
            </nav>
        {% else %}
            <strong>There are no categories present.</strong>
        {% endif %}
    </div>

    <hr/>
    <li></li>
    <h2>The Most Popular Articles</h2>
    <hr/>

         
            {% if articles %}
            <ul>
                {% for article in articles %}
                    {% if article.picture %}
                        &ensp;<a href="{% url 'article_reviewer:show_article' article.slug%}"><img src="{{ MEDIA_URL }}{{ article.picture }}" alt="{{ article.author }}"  width=30% height=%30/></a><a>{{ article.averageRating | floatformat:1 }}/5</a>&ensp;
                    {% else %}
                        &ensp;<a href="{% url 'article_reviewer:show_article' article.slug%}"><img src="{{ MEDIA_URL }}{{ article.category.picture }}" alt="{{ article.author }}"  width=30% height=%30/></a><a>{{ article.averageRating | floatformat:1 }}/5</a>&ensp;
                    {% endif %}
                {% endfor %}
            </ul>
            {% else %}
            <strong>There are no articles present.</strong>
            {% endif %}
        
{% endblock %}

templates/article_web_app/login.html
{% extends 'article_web_app/base.html' %}
{% load static %}

{% block title_block %}
    Sign In
{% endblock %}

{% block body_block %}
    <h1>Sign in for Article Reviewer</h1>
    <form id="login_form" method="post" action="{% url 'article_reviewer:login' %}">
        {% csrf_token %}
        Username: <input type="text" name="username" value="" size="50" />
        <br />
        Password: <input type="password" name="password" value="" size="50" />
        <br />
    <input type="submit" value="Sign In" />
</form>
{% endblock %}

templates/article_web_app/my_account.html
{% extends 'article_web_app/base.html' %}
{% load static %}

{% block title_block %}
    Article Reviewer
{% endblock %}

{% block body_block %}
    <h1>My Account Profile</h1>
    <div>
        <h3>Username: {{ user.username }}</h3>
        {% if user_profile.picture %}
            <img src="{{ MEDIA_URL }}{{ user_profile.picture }}" width="200" height="200"/></br>
        {% else %}
            <img src="{% static 'images/pfp-placeholder.png' %}"></br>
        {% endif %}
        <li><button onclick="addArticleFunction()" class="btn btn-primary"><p style= "font-size:x-large;font-weight: bold;"> Add Article </p></button></li>
    </div>
    <script>
        function addArticleFunction() {
            window.location="{% url 'article_reviewer:add_article' %}"
        }
    </script>
{% endblock %}

templates/article_web_app/review.html
{% extends 'article_web_app/base.html' %}
{% load static %}

{% block title_block %}
    Article Reviewer
{% endblock %}

{% block body_block %}
    
	<h1>Leave a comment and a Rating</h1>
    <form id="review_form" method="post" action="{% url 'article_reviewer:review' article.slug%}">
        {% csrf_token %}
        {{ review_form.as_p }}
    <input type="submit" value="Submit" />
{% endblock %}

templates/article_web_app/sign_up.html
{% extends 'article_web_app/base.html' %}
{% load static %}

{% block title_block %}
    Sign Up
{% endblock %}

{% block body_block %}
    <h1>Sign up for Article Reviewer</h1>
    {% if registered %}
        <strong>Thank you for registering!</strong>
    <a href="{% url 'article_reviewer:index' %}">Return to the homepage.</a><br />
    {% else %}
        <strong>register here!</strong><br />
        <form id="user_form" method="post" action="{% url 'article_reviewer:sign_up' %}" enctype="multipart/form-data">

            {% csrf_token %}

            {{ user_form.as_p }}
            {{ profile_form.as_p }}

            <input type="submit" name="submit" value="Sign Up" />
        </form>
    {% endif %}
{% endblock %}